# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resourcegroup: "tf-lab"
  storageacc: "abdusterrastore"
  stcontainer: "landing"
  storagekey: "devpipeline.terraform.tfstate"

stages:
  - stage: tfdestroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              backendServiceArm: 'Abdus Terraform Serv Conn'
              backendAzureRmResourceGroupName: 'tf-lab'
              backendAzureRmStorageAccountName: 'abdusterrastore'
              backendAzureRmContainerName: 'landing'
              backendAzureRmKey: 'devpipeline.terraform.tfstate'
          
          - task: TerraformTaskV4@4
            displayName: state
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              customCommand: 'terraform state list'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'Abdus Terraform Serv Conn'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              environmentServiceNameAzureRM: 'Abdus Terraform Serv Conn'
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              provider: 'azurerm'
              command: 'custom'
              customCommand: 'terraform destroy -auto-approve -target=azurerm_data_factory.gen_data_factory'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'Abdus Terraform Serv Conn'